// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR89YX8gineDIjLzRytvM1p0bMw63feDY',
    appId: '1:675827113063:web:b33d5cd235496053ad48c2',
    messagingSenderId: '675827113063',
    projectId: 'chattrail-56718',
    authDomain: 'chattrail-56718.firebaseapp.com',
    storageBucket: 'chattrail-56718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx2Pk3IwUoUnJzzbSbcCLE_-MMMwWyrwY',
    appId: '1:675827113063:android:d30db03b07bef948ad48c2',
    messagingSenderId: '675827113063',
    projectId: 'chattrail-56718',
    storageBucket: 'chattrail-56718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8dkqaoAcud2NqxQeHuq_jeWFa_MPlBsY',
    appId: '1:675827113063:ios:e8b8ceb7f53b2bd8ad48c2',
    messagingSenderId: '675827113063',
    projectId: 'chattrail-56718',
    storageBucket: 'chattrail-56718.appspot.com',
    iosBundleId: 'com.example.chatAppExample',
  );
}
